### ISSUE TITLE
email addresses containing a dot are marked as invalid.

### ISSUE THREAD

**Issue by everlaat** [panthershark/email-parser#1]
**Valid** email address examples;
`hel.lo@world.com`
`h.e.l.l.o@world.com`

**Invalid** email address examples;
locale can't start and/or end with a dot.
`.hello@world.com`
`hello.@world.com`
nor can it have more then two or more dots in a row
`he..llo@world.com`

**Comment by panthershark** [comment]
I'll incorporate these into the tests. Thanks!

**Comment by panthershark** [comment]
@everlaat  - please take a look at the PR. If you dont see anything weird, I'm happy to merge and publish.
