### ISSUE TITLE
Email addresses with more than 2 domainParts fail to parse

### ISSUE THREAD

**Issue by skyqrose** [panthershark/email-parser#2]
True, as expected:
```Elm
Email.isValid "user@one.two"
```

False, but I expected this to be valid:
```Elm
Email.isValid "user@one.two.three"
```

**Comment by panthershark** [comment]
I'll incorporate these into the tests. Thanks!

**Comment by panthershark** [comment]
@skyqrose - Please take a look at the PR. If you like it, I'll be happy to merge and publish the update.
